---
- name: "EOS Vlans using config and src"
  eos_config:
    src: templates/vlans.j2
  when: vlans is defined
  tags:
    - bridging
    - vlans

- name: "EOS Spanning-tree using config and src"
  eos_config:
    src: templates/spanning_tree.j2
  when:
     - spanning_tree is defined
  tags:
    - spanning_tree
    - bridging
    - vlans
