---
- name: "Include tasks based on ansbile_network_os"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_network_os }}_bridging.yml"
    - "bridging.yml"
  when:
    - vlans is defined
