---
- name: "Include tasks based on ansbile_network_os"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_network_os }}_interfaces.yml"
    - "interfaces.yml"
  when:
    - interfaces is defined
