---
- name: "Include tasks based on ansbile_network_os"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_network_os }}_l3_interfaces.yml"
    - "l3_interfaces.yml"
  when:
    - l3_interfaces is defined
